In [1]:
import numpy as np
import pandas as pd

In [2]:
movies = pd.read_csv('tmdb_5000_movies.csv')
credits = pd.read_csv('tmdb_5000_credits.csv')

In [3]:
movies.sample(1)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
344,100000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 53, ""nam...",NaN,44048,"[{""id"": 163228, ""name"": ""runaway train""}]",en,Unstoppable,"A runaway train, transporting deadly, toxic ch...",37.698465,"[{""name"": ""Twentieth Century Fox Film Corporat...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2010-11-04,167805466,98.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"1,000,000 Tons. 100,000 Lives. 100 Minutes.",Unstoppable,6.3,1165

In [4]:
credits.head(1)

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."

In [5]:
movies = movies.merge(credits, on='title')

In [6]:
type(movies)

pandas.core.frame.DataFrame

In [7]:
movies.head(1)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,movie_id,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,19995,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."

In [8]:
# genres
# id
# keywords
# overview
# cast 
# crew

movies = movies[['movie_id', 'title', 'overview', 'genres', 'keywords', 'cast', 'crew']]

In [9]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [10]:
movies.isnull().sum()

movie_id    0
title       0
overview    3
genres      0
keywords    0
cast        0
crew        0
dtype: int64

In [11]:
movies.dropna(inplace=True)

In [12]:
movies.duplicated().sum()

np.int64(0)

In [13]:
movies.iloc[0].genres

'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'

In [14]:
#'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'
# ['Action', 'Advanture', 'Fantacy', 'SiFi']

In [15]:
import ast

def convert(obj):
    L = []
    for i in ast.literal_eval(obj):
        L.append(i['name'])
    return L

In [16]:
movies['genres'] = movies['genres'].apply(convert)

In [17]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [18]:
movies['keywords'] = movies['keywords'].apply(convert)

In [19]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [20]:
movies['cast'][0]

'[{"cast_id": 242, "character": "Jake Sully", "credit_id": "5602a8a7c3a3685532001c9a", "gender": 2, "id": 65731, "name": "Sam Worthington", "order": 0}, {"cast_id": 3, "character": "Neytiri", "credit_id": "52fe48009251416c750ac9cb", "gender": 1, "id": 8691, "name": "Zoe Saldana", "order": 1}, {"cast_id": 25, "character": "Dr. Grace Augustine", "credit_id": "52fe48009251416c750aca39", "gender": 1, "id": 10205, "name": "Sigourney Weaver", "order": 2}, {"cast_id": 4, "character": "Col. Quaritch", "credit_id": "52fe48009251416c750ac9cf", "gender": 2, "id": 32747, "name": "Stephen Lang", "order": 3}, {"cast_id": 5, "character": "Trudy Chacon", "credit_id": "52fe48009251416c750ac9d3", "gender": 1, "id": 17647, "name": "Michelle Rodriguez", "order": 4}, {"cast_id": 8, "character": "Selfridge", "credit_id": "52fe48009251416c750ac9e1", "gender": 2, "id": 1771, "name": "Giovanni Ribisi", "order": 5}, {"cast_id": 7, "character": "Norm Spellman", "credit_id": "52fe48009251416c750ac9dd", "gender": 2, "id": 59231, "name": "Joel David Moore", "order": 6}, {"cast_id": 9, "character": "Moat", "credit_id": "52fe48009251416c750ac9e5", "gender": 1, "id": 30485, "name": "CCH Pounder", "order": 7}, {"cast_id": 11, "character": "Eytukan", "credit_id": "52fe48009251416c750ac9ed", "gender": 2, "id": 15853, "name": "Wes Studi", "order": 8}, {"cast_id": 10, "character": "Tsu\'Tey", "credit_id": "52fe48009251416c750ac9e9", "gender": 2, "id": 10964, "name": "Laz Alonso", "order": 9}, {"cast_id": 12, "character": "Dr. Max Patel", "credit_id": "52fe48009251416c750ac9f1", "gender": 2, "id": 95697, "name": "Dileep Rao", "order": 10}, {"cast_id": 13, "character": "Lyle Wainfleet", "credit_id": "52fe48009251416c750ac9f5", "gender": 2, "id": 98215, "name": "Matt Gerald", "order": 11}, {"cast_id": 32, "character": "Private Fike", "credit_id": "52fe48009251416c750aca5b", "gender": 2, "id": 154153, "name": "Sean Anthony Moran", "order": 12}, {"cast_id": 33, "character": "Cryo Vault Med Tech", "credit_id": "52fe48009251416c750aca5f", "gender": 2, "id": 397312, "name": "Jason Whyte", "order": 13}, {"cast_id": 34, "character": "Venture Star Crew Chief", "credit_id": "52fe48009251416c750aca63", "gender": 2, "id": 42317, "name": "Scott Lawrence", "order": 14}, {"cast_id": 35, "character": "Lock Up Trooper", "credit_id": "52fe48009251416c750aca67", "gender": 2, "id": 986734, "name": "Kelly Kilgour", "order": 15}, {"cast_id": 36, "character": "Shuttle Pilot", "credit_id": "52fe48009251416c750aca6b", "gender": 0, "id": 1207227, "name": "James Patrick Pitt", "order": 16}, {"cast_id": 37, "character": "Shuttle Co-Pilot", "credit_id": "52fe48009251416c750aca6f", "gender": 0, "id": 1180936, "name": "Sean Patrick Murphy", "order": 17}, {"cast_id": 38, "character": "Shuttle Crew Chief", "credit_id": "52fe48009251416c750aca73", "gender": 2, "id": 1019578, "name": "Peter Dillon", "order": 18}, {"cast_id": 39, "character": "Tractor Operator / Troupe", "credit_id": "52fe48009251416c750aca77", "gender": 0, "id": 91443, "name": "Kevin Dorman", "order": 19}, {"cast_id": 40, "character": "Dragon Gunship Pilot", "credit_id": "52fe48009251416c750aca7b", "gender": 2, "id": 173391, "name": "Kelson Henderson", "order": 20}, {"cast_id": 41, "character": "Dragon Gunship Gunner", "credit_id": "52fe48009251416c750aca7f", "gender": 0, "id": 1207236, "name": "David Van Horn", "order": 21}, {"cast_id": 42, "character": "Dragon Gunship Navigator", "credit_id": "52fe48009251416c750aca83", "gender": 0, "id": 215913, "name": "Jacob Tomuri", "order": 22}, {"cast_id": 43, "character": "Suit #1", "credit_id": "52fe48009251416c750aca87", "gender": 0, "id": 143206, "name": "Michael Blain-Rozgay", "order": 23}, {"cast_id": 44, "character": "Suit #2", "credit_id": "52fe48009251416c750aca8b", "gender": 2, "id": 169676, "name": "Jon Curry", "order": 24}, {"cast_id": 46, "character": "Ambient Room Tech", "credit_id": "52fe48009251416c750aca8f", "gender": 0, "id": 1048610, "name": "Luke Hawker", "order": 25}, {"cast_id": 47, "character": "Ambient Room Tech / Troupe", "credit_id": "52fe48009251416c750aca93", "gender": 0, "id": 42288, "name": "Woody Schultz", "order": 26}, {"cast_id": 48, "character": "Horse Clan Leader", "credit_id": "52fe48009251416c750aca97", "gender": 2, "id": 68278, "name": "Peter Mensah", "order": 27}, {"cast_id": 49, "character": "Link Room Tech", "credit_id": "52fe48009251416c750aca9b", "gender": 0, "id": 1207247, "name": "Sonia Yee", "order": 28}, {"cast_id": 50, "character": "Basketball Avatar / Troupe", "credit_id": "52fe48009251416c750aca9f", "gender": 1, "id": 1207248, "name": "Jahnel Curfman", "order": 29}, {"cast_id": 51, "character": "Basketball Avatar", "credit_id": "52fe48009251416c750acaa3", "gender": 0, "id": 89714, "name": "Ilram Choi", "order": 30}, {"cast_id": 52, "character": "Na\'vi Child", "credit_id": "52fe48009251416c750acaa7", "gender": 0, "id": 1207249, "name": "Kyla Warren", "order": 31}, {"cast_id": 53, "character": "Troupe", "credit_id": "52fe48009251416c750acaab", "gender": 0, "id": 1207250, "name": "Lisa Roumain", "order": 32}, {"cast_id": 54, "character": "Troupe", "credit_id": "52fe48009251416c750acaaf", "gender": 1, "id": 83105, "name": "Debra Wilson", "order": 33}, {"cast_id": 57, "character": "Troupe", "credit_id": "52fe48009251416c750acabb", "gender": 0, "id": 1207253, "name": "Chris Mala", "order": 34}, {"cast_id": 55, "character": "Troupe", "credit_id": "52fe48009251416c750acab3", "gender": 0, "id": 1207251, "name": "Taylor Kibby", "order": 35}, {"cast_id": 56, "character": "Troupe", "credit_id": "52fe48009251416c750acab7", "gender": 0, "id": 1207252, "name": "Jodie Landau", "order": 36}, {"cast_id": 58, "character": "Troupe", "credit_id": "52fe48009251416c750acabf", "gender": 0, "id": 1207254, "name": "Julie Lamm", "order": 37}, {"cast_id": 59, "character": "Troupe", "credit_id": "52fe48009251416c750acac3", "gender": 0, "id": 1207257, "name": "Cullen B. Madden", "order": 38}, {"cast_id": 60, "character": "Troupe", "credit_id": "52fe48009251416c750acac7", "gender": 0, "id": 1207259, "name": "Joseph Brady Madden", "order": 39}, {"cast_id": 61, "character": "Troupe", "credit_id": "52fe48009251416c750acacb", "gender": 0, "id": 1207262, "name": "Frankie Torres", "order": 40}, {"cast_id": 62, "character": "Troupe", "credit_id": "52fe48009251416c750acacf", "gender": 1, "id": 1158600, "name": "Austin Wilson", "order": 41}, {"cast_id": 63, "character": "Troupe", "credit_id": "52fe48019251416c750acad3", "gender": 1, "id": 983705, "name": "Sara Wilson", "order": 42}, {"cast_id": 64, "character": "Troupe", "credit_id": "52fe48019251416c750acad7", "gender": 0, "id": 1207263, "name": "Tamica Washington-Miller", "order": 43}, {"cast_id": 65, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acadb", "gender": 1, "id": 1145098, "name": "Lucy Briant", "order": 44}, {"cast_id": 66, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acadf", "gender": 2, "id": 33305, "name": "Nathan Meister", "order": 45}, {"cast_id": 67, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acae3", "gender": 0, "id": 1207264, "name": "Gerry Blair", "order": 46}, {"cast_id": 68, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acae7", "gender": 2, "id": 33311, "name": "Matthew Chamberlain", "order": 47}, {"cast_id": 69, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acaeb", "gender": 0, "id": 1207265, "name": "Paul Yates", "order": 48}, {"cast_id": 70, "character": "Op Center Duty Officer", "credit_id": "52fe48019251416c750acaef", "gender": 0, "id": 1207266, "name": "Wray Wilson", "order": 49}, {"cast_id": 71, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acaf3", "gender": 2, "id": 54492, "name": "James Gaylyn", "order": 50}, {"cast_id": 72, "character": "Dancer", "credit_id": "52fe48019251416c750acaf7", "gender": 0, "id": 1207267, "name": "Melvin Leno Clark III", "order": 51}, {"cast_id": 73, "character": "Dancer", "credit_id": "52fe48019251416c750acafb", "gender": 0, "id": 1207268, "name": "Carvon Futrell", "order": 52}, {"cast_id": 74, "character": "Dancer", "credit_id": "52fe48019251416c750acaff", "gender": 0, "id": 1207269, "name": "Brandon Jelkes", "order": 53}, {"cast_id": 75, "character": "Dancer", "credit_id": "52fe48019251416c750acb03", "gender": 0, "id": 1207270, "name": "Micah Moch", "order": 54}, {"cast_id": 76, "character": "Dancer", "credit_id": "52fe48019251416c750acb07", "gender": 0, "id": 1207271, "name": "Hanniyah Muhammad", "order": 55}, {"cast_id": 77, "character": "Dancer", "credit_id": "52fe48019251416c750acb0b", "gender": 0, "id": 1207272, "name": "Christopher Nolen", "order": 56}, {"cast_id": 78, "character": "Dancer", "credit_id": "52fe48019251416c750acb0f", "gender": 0, "id": 1207273, "name": "Christa Oliver", "order": 57}, {"cast_id": 79, "character": "Dancer", "credit_id": "52fe48019251416c750acb13", "gender": 0, "id": 1207274, "name": "April Marie Thomas", "order": 58}, {"cast_id": 80, "character": "Dancer", "credit_id": "52fe48019251416c750acb17", "gender": 0, "id": 1207275, "name": "Bravita A. Threatt", "order": 59}, {"cast_id": 81, "character": "Mining Chief (uncredited)", "credit_id": "52fe48019251416c750acb1b", "gender": 0, "id": 1207276, "name": "Colin Bleasdale", "order": 60}, {"cast_id": 82, "character": "Veteran Miner (uncredited)", "credit_id": "52fe48019251416c750acb1f", "gender": 0, "id": 107969, "name": "Mike Bodnar", "order": 61}, {"cast_id": 83, "character": "Richard (uncredited)", "credit_id": "52fe48019251416c750acb23", "gender": 0, "id": 1207278, "name": "Matt Clayton", "order": 62}, {"cast_id": 84, "character": "Nav\'i (uncredited)", "credit_id": "52fe48019251416c750acb27", "gender": 1, "id": 147898, "name": "Nicole Dionne", "order": 63}, {"cast_id": 85, "character": "Trooper (uncredited)", "credit_id": "52fe48019251416c750acb2b", "gender": 0, "id": 1207280, "name": "Jamie Harrison", "order": 64}, {"cast_id": 86, "character": "Trooper (uncredited)", "credit_id": "52fe48019251416c750acb2f", "gender": 0, "id": 1207281, "name": "Allan Henry", "order": 65}, {"cast_id": 87, "character": "Ground Technician (uncredited)", "credit_id": "52fe48019251416c750acb33", "gender": 2, "id": 1207282, "name": "Anthony Ingruber", "order": 66}, {"cast_id": 88, "character": "Flight Crew Mechanic (uncredited)", "credit_id": "52fe48019251416c750acb37", "gender": 0, "id": 1207283, "name": "Ashley Jeffery", "order": 67}, {"cast_id": 14, "character": "Samson Pilot", "credit_id": "52fe48009251416c750ac9f9", "gender": 0, "id": 98216, "name": "Dean Knowsley", "order": 68}, {"cast_id": 89, "character": "Trooper (uncredited)", "credit_id": "52fe48019251416c750acb3b", "gender": 0, "id": 1201399, "name": "Joseph Mika-Hunt", "order": 69}, {"cast_id": 90, "character": "Banshee (uncredited)", "credit_id": "52fe48019251416c750acb3f", "gender": 0, "id": 236696, "name": "Terry Notary", "order": 70}, {"cast_id": 91, "character": "Soldier (uncredited)", "credit_id": "52fe48019251416c750acb43", "gender": 0, "id": 1207287, "name": "Kai Pantano", "order": 71}, {"cast_id": 92, "character": "Blast Technician (uncredited)", "credit_id": "52fe48019251416c750acb47", "gender": 0, "id": 1207288, "name": "Logan Pithyou", "order": 72}, {"cast_id": 93, "character": "Vindum Raah (uncredited)", "credit_id": "52fe48019251416c750acb4b", "gender": 0, "id": 1207289, "name": "Stuart Pollock", "order": 73}, {"cast_id": 94, "character": "Hero (uncredited)", "credit_id": "52fe48019251416c750acb4f", "gender": 0, "id": 584868, "name": "Raja", "order": 74}, {"cast_id": 95, "character": "Ops Centreworker (uncredited)", "credit_id": "52fe48019251416c750acb53", "gender": 0, "id": 1207290, "name": "Gareth Ruck", "order": 75}, {"cast_id": 96, "character": "Engineer (uncredited)", "credit_id": "52fe48019251416c750acb57", "gender": 0, "id": 1062463, "name": "Rhian Sheehan", "order": 76}, {"cast_id": 97, "character": "Col. Quaritch\'s Mech Suit (uncredited)", "credit_id": "52fe48019251416c750acb5b", "gender": 0, "id": 60656, "name": "T. J. Storm", "order": 77}, {"cast_id": 98, "character": "Female Marine (uncredited)", "credit_id": "52fe48019251416c750acb5f", "gender": 0, "id": 1207291, "name": "Jodie Taylor", "order": 78}, {"cast_id": 99, "character": "Ikran Clan Leader (uncredited)", "credit_id": "52fe48019251416c750acb63", "gender": 1, "id": 1186027, "name": "Alicia Vela-Bailey", "order": 79}, {"cast_id": 100, "character": "Geologist (uncredited)", "credit_id": "52fe48019251416c750acb67", "gender": 0, "id": 1207292, "name": "Richard Whiteside", "order": 80}, {"cast_id": 101, "character": "Na\'vi (uncredited)", "credit_id": "52fe48019251416c750acb6b", "gender": 0, "id": 103259, "name": "Nikie Zambo", "order": 81}, {"cast_id": 102, "character": "Ambient Room Tech / Troupe", "credit_id": "52fe48019251416c750acb6f", "gender": 1, "id": 42286, "name": "Julene Renee", "order": 82}]'

In [21]:
# for cast top 3 actors

In [22]:
import ast

def convert3(obj):
    L = []
    counter = 0
    for i in ast.literal_eval(obj):
        if counter != 3:
            L.append(i['name'])
        else:
            break
    return L

In [23]:
movies['cast'] = movies['cast'].apply(convert3)

In [24]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weave...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley, ...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, Léa Seydoux, R...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman, A...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton,...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [25]:
import ast

def fetch_director(obj):
    L = []
    for i in ast.literal_eval(obj):
        if i['job'] == 'Director':
            L.append(i['name']) 
            break
            
    return L

In [26]:
movies['crew'] = movies['crew'].apply(fetch_director)

In [27]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weave...",[James Cameron]
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley, ...",[Gore Verbinski]
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, Léa Seydoux, R...",[Sam Mendes]
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman, A...",[Christopher Nolan]
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton,...",[Andrew Stanton]

In [28]:
movies['crew'][0]

['James Cameron']

In [29]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weave...",[James Cameron]
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley, ...",[Gore Verbinski]
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, Léa Seydoux, R...",[Sam Mendes]
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman, A...",[Christopher Nolan]
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton,...",[Andrew Stanton]

In [30]:
movies['overview'][0]

'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization.'

In [31]:
movies['overview'] = movies['overview'].apply(lambda X:X.split())

In [32]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weave...",[James Cameron]
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley, ...",[Gore Verbinski]
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, Léa Seydoux, R...",[Sam Mendes]
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman, A...",[Christopher Nolan]
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton,...",[Andrew Stanton]

In [33]:
movies['genres'] = movies['genres'].apply(lambda x:[i.replace(" ", "") for i in x])
movies['keywords'] = movies['keywords'].apply(lambda x:[i.replace(" ", "") for i in x])
movies['cast'] = movies['crew'].apply(lambda x:[i.replace(" ", "") for i in x])
movies['crew'] = movies['crew'].apply(lambda x:[i.replace(" ", "") for i in x])

In [34]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...",[JamesCameron],[JamesCameron]
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...",[GoreVerbinski],[GoreVerbinski]
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...",[SamMendes],[SamMendes]
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dccomics, crimefighter, terrorist, secretiden...",[ChristopherNolan],[ChristopherNolan]
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, ScienceFiction]","[basedonnovel, mars, medallion, spacetravel, p...",[AndrewStanton],[AndrewStanton]

In [35]:
movies['tags'] = movies['overview'] + movies['genres'] + movies['keywords'] + movies['cast'] + movies['crew']

In [36]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew,tags
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...",[JamesCameron],[JamesCameron],"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...",[GoreVerbinski],[GoreVerbinski],"[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...",[SamMendes],[SamMendes],"[A, cryptic, message, from, Bond’s, past, send..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dccomics, crimefighter, terrorist, secretiden...",[ChristopherNolan],[ChristopherNolan],"[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, ScienceFiction]","[basedonnovel, mars, medallion, spacetravel, p...",[AndrewStanton],[AndrewStanton],"[John, Carter, is, a, war-weary,, former, mili..."

In [37]:
new_df = movies[['movie_id', 'title', 'tags']]

In [38]:
new_df

,movie_id,title,tags
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili..."
...,...,...,...
4804,9367,El Mariachi,"[El, Mariachi, just, wants, to, play, his, gui..."
4805,72766,Newlyweds,"[A, newlywed, couple's, honeymoon, is, upended..."
4806,231617,"Signed, Sealed, Delivered","[""Signed,, Sealed,, Delivered"", introduces, a,..."
4807,126186,Shanghai Calling,"[When, ambitious, New, York, attorney, Sam, is..."
4808,25975,My Date with Drew,"[Ever, since, the, second, grade, when, he, fi..."

In [39]:
new_df['tags'] = new_df['tags'].apply(lambda x:" ".join(x))

C:\Users\Sujala Rai\AppData\Local\Temp\ipykernel_39236\3089450492.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(lambda x:" ".join(x))

In [40]:
new_df.head()

,movie_id,title,tags
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...
4,49529,John Carter,"John Carter is a war-weary, former military ca..."

In [57]:
import nltk

In [59]:
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()

In [65]:
def stem(text):
    y = []

    for i in text.split():
        y.append(ps.stem(i))

    return " ".join(y)

In [69]:
new_df['tags'] = new_df['tags'].apply(stem)

C:\Users\Sujala Rai\AppData\Local\Temp\ipykernel_39236\3213734980.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(stem)

In [70]:
new_df['tags'][0]

'in the 22nd century, a parapleg marin is dispatch to the moon pandora on a uniqu mission, but becom torn between follow order and protect an alien civilization. action adventur fantasi sciencefict cultureclash futur spacewar spacecoloni societi spacetravel futurist romanc space alien tribe alienplanet cgi marin soldier battl loveaffair antiwar powerrel mindandsoul 3d jamescameron jamescameron'

In [71]:
new_df['tags'] = new_df['tags'].apply(lambda x:x.lower())

C:\Users\Sujala Rai\AppData\Local\Temp\ipykernel_39236\3214958533.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(lambda x:x.lower())

In [73]:
new_df.head()

,movie_id,title,tags
0,19995,Avatar,"in the 22nd century, a parapleg marin is dispa..."
1,285,Pirates of the Caribbean: At World's End,"captain barbossa, long believ to be dead, ha c..."
2,206647,Spectre,a cryptic messag from bond’ past send him on a...
3,49026,The Dark Knight Rises,follow the death of district attorney harvey d...
4,49529,John Carter,"john carter is a war-weary, former militari ca..."

In [74]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=5000, stop_words='english')

In [75]:
vectors = cv.fit_transform(new_df['tags']).toarray()

In [76]:
vectors

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], shape=(4806, 5000))

In [77]:
cv.get_feature_names_out()

array(['000', '007', '10', ..., 'zombies', 'zone', 'zoo'],
      shape=(5000,), dtype=object)

In [78]:
ps.stem('loving')

'love'

In [79]:
stem('in the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. Action Adventure Fantasy ScienceFiction cultureclash future spacewar spacecolony society spacetravel futuristic romance space alien tribe alienplanet cgi marine soldier battle loveaffair antiwar powerrelations mindandsoul 3d JamesCameron JamesCameron')

'in the 22nd century, a parapleg marin is dispatch to the moon pandora on a uniqu mission, but becom torn between follow order and protect an alien civilization. action adventur fantasi sciencefict cultureclash futur spacewar spacecoloni societi spacetravel futurist romanc space alien tribe alienplanet cgi marin soldier battl loveaffair antiwar powerrel mindandsoul 3d jamescameron jamescameron'

In [80]:
from sklearn.metrics.pairwise import cosine_similarity

In [83]:
similarity = cosine_similarity(vectors)

In [82]:
cosine_similarity(vectors).shape

(4806, 4806)

In [91]:
sorted(list(enumerate(similarity[0])), reverse=True, key=lambda x:x[1])[1:6]

[(2405, np.float64(0.3069249070224257)),
 (1214, np.float64(0.2811237422961876)),
 (539, np.float64(0.25883878884437284)),
 (3728, np.float64(0.25715142542972574)),
 (507, np.float64(0.25231028011870793))]

In [88]:
sorted(similarity[0], reverse=True)

[np.float64(1.0),
 np.float64(0.3069249070224257),
 np.float64(0.2811237422961876),
 np.float64(0.25883878884437284),
 np.float64(0.25715142542972574),
 np.float64(0.25231028011870793),
 np.float64(0.24140227479263376),
 np.float64(0.23537827088100213),
 np.float64(0.22422426466543746),
 np.float64(0.22417941532712204),
 np.float64(0.22337423731498202),
 np.float64(0.21982600255746473),
 np.float64(0.21571674297647797),
 np.float64(0.21021382614017325),
 np.float64(0.20254787341673336),
 np.float64(0.20174251088960077),
 np.float64(0.20033416898825337),
 np.float64(0.20033416898825335),
 np.float64(0.19985201625794738),
 np.float64(0.19814848097530421),
 np.float64(0.19814848097530421),
 np.float64(0.19795764159656265),
 np.float64(0.19693159036084404),
 np.float64(0.19611613513818404),
 np.float64(0.19418390934515434),
 np.float64(0.19223226273338137),
 np.float64(0.19215378456610455),
 np.float64(0.18741582819745836),
 np.float64(0.18685673434682068),
 np.float64(0.18490006540840973),
 np.float64(0.1849000654084097),
 np.float64(0.18452078282356416),
 np.float64(0.18427434427242975),
 np.float64(0.1815682598006407),
 np.float64(0.18116432546313532),
 np.float64(0.18014417303072303),
 np.float64(0.17937941173234997),
 np.float64(0.17841031003501576),
 np.float64(0.17722938923964168),
 np.float64(0.17471413945365305),
 np.float64(0.17295817388759027),
 np.float64(0.17255919256291524),
 np.float64(0.17255919256291524),
 np.float64(0.1710334403066895),
 np.float64(0.17093520167692652),
 np.float64(0.1706971854997297),
 np.float64(0.1706971854997297),
 np.float64(0.16898159235484367),
 np.float64(0.16898159235484367),
 np.float64(0.16898159235484367),
 np.float64(0.167093470609201),
 np.float64(0.16526725762745997),
 np.float64(0.16477051091432687),
 np.float64(0.1634996425534681),
 np.float64(0.1634301126151534),
 np.float64(0.1634301126151534),
 np.float64(0.16269036695641684),
 np.float64(0.16239958858823),
 np.float64(0.1617875572323585),
 np.float64(0.16012815380508713),
 np.float64(0.16012815380508713),
 np.float64(0.1601281538050871),
 np.float64(0.1601281538050871),
 np.float64(0.1601281538050871),
 np.float64(0.1585187847802434),
 np.float64(0.15818713475337637),
 np.float64(0.15794943794779692),
 np.float64(0.15701857325533194),
 np.float64(0.15695698526580623),
 np.float64(0.15695698526580623),
 np.float64(0.15585730003983933),
 np.float64(0.15534712747612348),
 np.float64(0.15311180047019055),
 np.float64(0.15253477177414312),
 np.float64(0.15191090506255),
 np.float64(0.15004689698410661),
 np.float64(0.1500468969841066),
 np.float64(0.14867525836251314),
 np.float64(0.14867525836251314),
 np.float64(0.14824986333222023),
 np.float64(0.14651588715165131),
 np.float64(0.14617633655117152),
 np.float64(0.14617633655117152),
 np.float64(0.14617633655117152),
 np.float64(0.14484136487558028),
 np.float64(0.14484136487558028),
 np.float64(0.14484136487558028),
 np.float64(0.14484136487558028),
 np.float64(0.14470719035407653),
 np.float64(0.1447071903540765),
 np.float64(0.1447071903540765),
 np.float64(0.14351616441832768),
 np.float64(0.14322297480788657),
 np.float64(0.14322297480788657),
 np.float64(0.14322297480788657),
 np.float64(0.14322297480788657),
 np.float64(0.14322297480788657),
 np.float64(0.14322297480788657),
 np.float64(0.1416576493949657),
 np.float64(0.14153462926807445),
 np.float64(0.14153462926807445),
 np.float64(0.14121975762272054),
 np.float64(0.13977131156292244),
 np.float64(0.13937366833451514),
 np.float64(0.13937366833451512),
 np.float64(0.1386750490563073),
 np.float64(0.1386750490563073),
 np.float64(0.1373087590952724),
 np.float64(0.1373087590952724),
 np.float64(0.1373087590952724),
 np.float64(0.13655774839978377),
 np.float64(0.13655774839978377),
 np.float64(0.13655774839978377),
 np.float64(0.13592873654160803),
 np.float64(0.13533299049019168),
 np.float64(0.13533299049019168),
 np.float64(0.13533299049019168),
 np.float64(0.13533299049019168),
 np.float64(0.1345345587992625),
 np.float64(0.1345345587992625),
 np.float64(0.13355611265883557),
 np.float64(0.13355611265883557),
 np.float64(0.13355611265883557),
 np.float64(0.13344012817090595),
 np.float64(0.13323467750529824),
 np.float64(0.1319717610643751),
 np.float64(0.1316245316231641),
 np.float64(0.13119107973822086),
 np.float64(0.13119107973822086),
 np.float64(0.1307440900921227),
 np.float64(0.1307440900921227),
 np.float64(0.1307440900921227),
 np.float64(0.1307440900921227),
 np.float64(0.1307440900921227),
 np.float64(0.13074409009212268),
 np.float64(0.12988108336653278),
 np.float64(0.1283881477532739),
 np.float64(0.1283881477532739),
 np.float64(0.12820512820512822),
 np.float64(0.1282051282051282),
 np.float64(0.1282051282051282),
 np.float64(0.1282051282051282),
 np.float64(0.1282051282051282),
 np.float64(0.12810252304406972),
 np.float64(0.12810252304406972),
 np.float64(0.12810252304406972),
 np.float64(0.12810252304406972),
 np.float64(0.12659242088545833),
 np.float64(0.12659242088545833),
 np.float64(0.12659242088545833),
 np.float64(0.12659242088545833),
 np.float64(0.126155140059354),
 np.float64(0.12561485860426555),
 np.float64(0.12508145976752497),
 np.float64(0.12503908082008883),
 np.float64(0.12503908082008883),
 np.float64(0.12503908082008883),
 np.float64(0.1235415527768502),
 np.float64(0.12326671027227314),
 np.float64(0.12326671027227314),
 np.float64(0.12326671027227314),
 np.float64(0.12326671027227314),
 np.float64(0.12301385521570944),
 np.float64(0.12209657262637609),
 np.float64(0.12209657262637609),
 np.float64(0.12209657262637609),
 np.float64(0.12104550653376048),
 np.float64(0.12104550653376048),
 np.float64(0.12104550653376046),
 np.float64(0.12104550653376046),
 np.float64(0.1207011373963169),
 np.float64(0.12009611535381534),
 np.float64(0.12009611535381534),
 np.float64(0.11935247900657214),
 np.float64(0.11935247900657214),
 np.float64(0.11894020669001051),
 np.float64(0.11894020669001051),
 np.float64(0.1182624791978165),
 np.float64(0.11804804116247142),
 np.float64(0.11694106924093722),
 np.float64(0.11694106924093722),
 np.float64(0.11694106924093722),
 np.float64(0.11686159857648114),
 np.float64(0.11651034560709261),
 np.float64(0.11651034560709261),
 np.float64(0.11651034560709261),
 np.float64(0.11651034560709261),
 np.float64(0.11651034560709261),
 np.float64(0.1165103456070926),
 np.float64(0.1165103456070926),
 np.float64(0.1165103456070926),
 np.float64(0.11556254088025608),
 np.float64(0.11556254088025608),
 np.float64(0.11556254088025608),
 np.float64(0.11556254088025608),
 np.float64(0.11556254088025608),
 np.float64(0.11503946170861017),
 np.float64(0.11503946170861017),
 np.float64(0.11503946170861017),
 np.float64(0.11503946170861017),
 np.float64(0.11483385035264292),
 np.float64(0.11437725271791938),
 np.float64(0.11437725271791938),
 np.float64(0.11437725271791938),
 np.float64(0.11437725271791938),
 np.float64(0.11357879791107997),
 np.float64(0.11322770341445958),
 np.float64(0.11322770341445958),
 np.float64(0.11322770341445958),
 np.float64(0.11322770341445956),
 np.float64(0.11322770341445956),
 np.float64(0.11322770341445956),
 np.float64(0.11322770341445956),
 np.float64(0.11322770341445956),
 np.float64(0.11265439490322912),
 np.float64(0.11211213233271873),
 np.float64(0.11168711865749101),
 np.float64(0.11168711865749101),
 np.float64(0.11149893466761211),
 np.float64(0.11102889792108189),
 np.float64(0.11102889792108188),
 np.float64(0.11094003924504581),
 np.float64(0.11020775375559674),
 np.float64(0.11020775375559674),
 np.float64(0.11020775375559674),
 np.float64(0.11020775375559674),
 np.float64(0.10997646755364592),
 np.float64(0.10997646755364592),
 np.float64(0.10991300127873235),
 np.float64(0.10984700727621793),
 np.float64(0.10984700727621793),
 np.float64(0.10984700727621793),
 np.float64(0.10984700727621793),
 np.float64(0.10984700727621793),
 np.float64(0.10948978029027179),
 np.float64(0.10895340841010223),
 np.float64(0.10895340841010223),
 np.float64(0.10895340841010223),
 np.float64(0.10895340841010223),
 np.float64(0.10887114836937548),
 np.float64(0.10826639239215335),
 np.float64(0.10826639239215334),
 np.float64(0.10826639239215334),
 np.float64(0.10826639239215334),
 np.float64(0.10826639239215334),
 np.float64(0.108094949066235),
 np.float64(0.10795837927188262),
 np.float64(0.10795837927188262),
 np.float64(0.10795837927188262),
 np.float64(0.10741723110591493),
 np.float64(0.10741723110591492),
 np.float64(0.10741723110591492),
 np.float64(0.10741723110591492),
 np.float64(0.10741723110591492),
 np.float64(0.10741723110591492),
 np.float64(0.10699012312772824),
 np.float64(0.10699012312772824),
 np.float64(0.10675210253672476),
 np.float64(0.10675210253672475),
 np.float64(0.10675210253672475),
 np.float64(0.10675210253672475),
 np.float64(0.10675210253672475),
 np.float64(0.10675210253672475),
 np.float64(0.10675210253672475),
 np.float64(0.10675210253672475),
 np.float64(0.10675210253672475),
 np.float64(0.10604746049596295),
 np.float64(0.10545808983558423),
 np.float64(0.10529962529853128),
 np.float64(0.105129283382795),
 np.float64(0.105129283382795),
 np.float64(0.10482848367219183),
 np.float64(0.10482848367219183),
 np.float64(0.10482848367219183),
 np.float64(0.10482848367219183),
 np.float64(0.10482848367219183),
 np.float64(0.10390486669322622),
 np.float64(0.10390486669322622),
 np.float64(0.10390486669322622),
 np.float64(0.10390486669322622),
 np.float64(0.10390486669322622),
 np.float64(0.10390486669322622),
 np.float64(0.10360237735649558),
 np.float64(0.10336227882434038),
 np.float64(0.10336227882434038),
 np.float64(0.10256410256410256),
 np.float64(0.1025115460130912),
 np.float64(0.1025115460130912),
 np.float64(0.10241831129983783),
 np.float64(0.10241831129983783),
 np.float64(0.10241831129983783),
 np.float64(0.10168147934776052),
 np.float64(0.10127393670836667),
 np.float64(0.10127393670836667),
 np.float64(0.10127393670836667),
 np.float64(0.10127393670836667),
 np.float64(0.10127393670836667),
 np.float64(0.10127393670836667),
 np.float64(0.10127393670836667),
 np.float64(0.10127393670836667),
 np.float64(0.10087125544480038),
 np.float64(0.10087125544480038),
 np.float64(0.10071594933968879),
 np.float64(0.10016708449412667),
 np.float64(0.10016708449412667),
 np.float64(0.10016708449412667),
 np.float64(0.10016708449412667),
 np.float64(0.10016708449412667),
 np.float64(0.10016708449412667),
 np.float64(0.10016708449412667),
 np.float64(0.10008009612817946),
 np.float64(0.10008009612817945),
 np.float64(0.10003126465607107),
 np.float64(0.10003126465607107),
 np.float64(0.09883324222148016),
 np.float64(0.09883324222148016),
 np.float64(0.09883324222148016),
 np.float64(0.09883324222148016),
 np.float64(0.09883324222148016),
 np.float64(0.09883324222148016),
 np.float64(0.09883324222148016),
 np.float64(0.09855206599818042),
 np.float64(0.09805806756909202),
 np.float64(0.09805806756909202),
 np.float64(0.09805806756909202),
 np.float64(0.09805806756909202),
 np.float64(0.09805806756909202),
 np.float64(0.09805806756909202),
 np.float64(0.09805806756909202),
 np.float64(0.09805806756909202),
 np.float64(0.09805806756909202),
 np.float64(0.09805806756909202),
 np.float64(0.09767725810110087),
 np.float64(0.09767725810110087),
 np.float64(0.09767725810110087),
 np.float64(0.09767725810110087),
 np.float64(0.09767725810110087),
 np.float64(0.09767725810110087),
 np.float64(0.09709195467257717),
 np.float64(0.09709195467257717),
 np.float64(0.09656090991705352),
 np.float64(0.09656090991705352),
 np.float64(0.09656090991705352),
 np.float64(0.09656090991705352),
 np.float64(0.09638582199437336),
 np.float64(0.09607689228305229),
 np.float64(0.09607689228305229),
 np.float64(0.09607689228305229),
 np.float64(0.09607689228305229),
 np.float64(0.09607689228305229),
 np.float64(0.09607689228305229),
 np.float64(0.09607689228305229),
 np.float64(0.0956948752938691),
 np.float64(0.09548198320525772),
 np.float64(0.09443843292997713),
 np.float64(0.09443843292997713),
 np.float64(0.09443843292997713),
 np.float64(0.09443843292997713),
 np.float64(0.09443843292997713),
 np.float64(0.09443843292997713),
 np.float64(0.09435641951204965),
 np.float64(0.09421114395319916),
 np.float64(0.09421114395319916),
 np.float64(0.09421114395319916),
 np.float64(0.09421114395319916),
 np.float64(0.09421114395319916),
 np.float64(0.09421114395319916),
 np.float64(0.09370791409872918),
 np.float64(0.09342836717341035),
 np.float64(0.09342836717341034),
 np.float64(0.09342836717341034),
 np.float64(0.09342836717341034),
 np.float64(0.09342836717341034),
 np.float64(0.0930725988812425),
 np.float64(0.09245003270420486),
 np.float64(0.09245003270420486),
 np.float64(0.09245003270420486),
 np.float64(0.09245003270420486),
 np.float64(0.09245003270420486),
 np.float64(0.09245003270420486),
 np.float64(0.09245003270420486),
 np.float64(0.09245003270420486),
 np.float64(0.09245003270420485),
 np.float64(0.09245003270420485),
 np.float64(0.09245003270420485),
 np.float64(0.09245003270420485),
 np.float64(0.09245003270420485),
 np.float64(0.09245003270420485),
 np.float64(0.09245003270420485),
 np.float64(0.09245003270420485),
 np.float64(0.09245003270420485),
 np.float64(0.09245003270420485),
 np.float64(0.09183979479633063),
 np.float64(0.0915018021743355),
 np.float64(0.0915018021743355),
 np.float64(0.0915018021743355),
 np.float64(0.09078412990032037),
 np.float64(0.09078412990032037),
 np.float64(0.09078412990032037),
 np.float64(0.09078412990032037),
 np.float64(0.09078412990032037),
 np.float64(0.09078412990032037),
 np.float64(0.09078412990032037),
 np.float64(0.09065471553673685),
 np.float64(0.09065471553673685),
 np.float64(0.09058216273156766),
 np.float64(0.09058216273156766),
 np.float64(0.09058216273156766),
 np.float64(0.09058216273156766),
 np.float64(0.09058216273156766),
 np.float64(0.09058216273156766),
 np.float64(0.09058216273156766),
 np.float64(0.09058216273156766),
 np.float64(0.09058216273156766),
 np.float64(0.0900791242218625),
 np.float64(0.08968970586617499),
 np.float64(0.08968970586617499),
 np.float64(0.08968970586617499),
 np.float64(0.08968970586617499),
 np.float64(0.08968970586617499),
 np.float64(0.08951435925492911),
 np.float64(0.08920515501750789),
 np.float64(0.08920515501750789),
 np.float64(0.08920515501750789),
 np.float64(0.08920515501750789),
 np.float64(0.08920515501750789),
 np.float64(0.08920515501750789),
 np.float64(0.08920515501750789),
 np.float64(0.08920515501750789),
 np.float64(0.08920515501750789),
 np.float64(0.08920515501750789),
 np.float64(0.0888231183368655),
 np.float64(0.0888231183368655),
 np.float64(0.0888231183368655),
 np.float64(0.0888231183368655),
 np.float64(0.0888231183368655),
 np.float64(0.0888231183368655),
 np.float64(0.08806599154457967),
 np.float64(0.08798117404291673),
 np.float64(0.08798117404291673),
 np.float64(0.08798117404291673),
 np.float64(0.08798117404291673),
 np.float64(0.08788174152965353),
 np.float64(0.08788174152965353),
 np.float64(0.08770580193070292),
 np.float64(0.08770580193070292),
 np.float64(0.08770580193070292),
 np.float64(0.08770580193070292),
 np.float64(0.08770580193070292),
 np.float64(0.08770580193070292),
 np.float64(0.08770580193070292),
 np.float64(0.08770580193070292),
 np.float64(0.08770580193070292),
 np.float64(0.08770580193070292),
 np.float64(0.08735706972682653),
 np.float64(0.08735706972682653),
 np.float64(0.08716272672808179),
 np.float64(0.08716272672808179),
 np.float64(0.08716272672808179),
 np.float64(0.08716272672808179),
 np.float64(0.0863667034175061),
 np.float64(0.0863667034175061),
 np.float64(0.0863667034175061),
 np.float64(0.0863667034175061),
 np.float64(0.08627959628145762),
 np.float64(0.08627959628145762),
 np.float64(0.08627959628145762),
 np.float64(0.08627959628145762),
 np.float64(0.08627959628145762),
 np.float64(0.08559209850218259),
 np.float64(0.08559209850218259),
 np.float64(0.08559209850218259),
 np.float64(0.08559209850218259),
 np.float64(0.08559209850218259),
 np.float64(0.08559209850218259),
 np.float64(0.08559209850218259),
 np.float64(0.08492077756084468),
 np.float64(0.08492077756084468),
 np.float64(0.08492077756084468),
 np.float64(0.08492077756084468),
 np.float64(0.08492077756084468),
 np.float64(0.08492077756084468),
 np.float64(0.08492077756084468),
 np.float64(0.08492077756084468),
 np.float64(0.08492077756084468),
 np.float64(0.08492077756084468),
 np.float64(0.08492077756084468),
 np.float64(0.08483796839677037),
 np.float64(0.08483796839677037),
 np.float64(0.084103426706236),
 np.float64(0.084103426706236),
 np.float64(0.084103426706236),
 np.float64(0.08362420100070908),
 np.float64(0.08362420100070908),
 np.float64(0.08362420100070908),
 np.float64(0.08362420100070908),
 np.float64(0.08362420100070908),
 np.float64(0.08338763984501665),
 np.float64(0.08338763984501665),
 np.float64(0.08338763984501665),
 np.float64(0.08338763984501665),
 np.float64(0.0826898230594723),
 np.float64(0.0826898230594723),
 np.float64(0.0826898230594723),
 np.float64(0.0826898230594723),
 np.float64(0.0826898230594723),
 np.float64(0.0826898230594723),
 np.float64(0.0826898230594723),
 np.float64(0.08238525545716345),
 np.float64(0.08238525545716345),
 np.float64(0.08238525545716345),
 np.float64(0.08238525545716345),
 np.float64(0.08238525545716345),
 np.float64(0.08238525545716345),
 np.float64(0.08238525545716345),
 np.float64(0.08238525545716345),
 np.float64(0.08238525545716345),
 np.float64(0.08200923681047297),
 np.float64(0.08200923681047297),
 np.float64(0.08200923681047297),
 np.float64(0.08200923681047297),
 np.float64(0.08134518347820842),
 np.float64(0.08119979429411502),
 np.float64(0.081199794294115),
 np.float64(0.081199794294115),
 np.float64(0.081199794294115),
 np.float64(0.081199794294115),
 np.float64(0.081199794294115),
 np.float64(0.08087693101032827),
 np.float64(0.08069700435584032),
 np.float64(0.0806970043558403),
 np.float64(0.0806970043558403),
 np.float64(0.0806970043558403),
 np.float64(0.08006407690254357),
 np.float64(0.08006407690254357),
 np.float64(0.08006407690254357),
 np.float64(0.08006407690254357),
 np.float64(0.08006407690254357),
 np.float64(0.08006407690254357),
 np.float64(0.08006407690254357),
 np.float64(0.08006407690254357),
 np.float64(0.08006407690254357),
 np.float64(0.08006407690254357),
 np.float64(0.08006407690254357),
 np.float64(0.08006407690254357),
 np.float64(0.08006407690254357),
 np.float64(0.08006407690254357),
 np.float64(0.08006407690254357),
 np.float64(0.08006407690254357),
 np.float64(0.08006407690254357),
 np.float64(0.08006407690254357),
 np.float64(0.08006407690254357),
 np.float64(0.07944581222989573),
 np.float64(0.07944581222989573),
 np.float64(0.07897471897389846),
 np.float64(0.07897471897389846),
 np.float64(0.07897471897389846),
 np.float64(0.07897471897389846),
 np.float64(0.07897471897389846),
 np.float64(0.07897471897389846),
 np.float64(0.07897471897389846),
 np.float64(0.07897471897389846),
 np.float64(0.07884165279854434),
 np.float64(0.0782510703046739),
 np.float64(0.0782510703046739),
 np.float64(0.07813453848974924),
 np.float64(0.07792865001991967),
 np.float64(0.07792865001991967),
 np.float64(0.07792865001991967),
 np.float64(0.07792865001991967),
 np.float64(0.07792865001991967),
 np.float64(0.07792865001991967),
 np.float64(0.07792865001991967),
 np.float64(0.07792865001991967),
 np.float64(0.07792865001991967),
 np.float64(0.07792865001991967),
 np.float64(0.07792865001991967),
 np.float64(0.07767356373806174),
 np.float64(0.07767356373806174),
 np.float64(0.07767356373806174),
 np.float64(0.07767356373806174),
 np.float64(0.07767356373806174),
 np.float64(0.07767356373806174),
 np.float64(0.07767356373806174),
 np.float64(0.07767356373806174),
 np.float64(0.07767356373806174),
 np.float64(0.07710865759549869),
 np.float64(0.07710865759549869),
 np.float64(0.07710865759549869),
 np.float64(0.07710865759549869),
 np.float64(0.07704169392017071),

In [97]:
def recommend(movie):
    movie_index = new_df[new_df['title'] == movie].index[0]
    distences = similarity[movie_index]
    movies_list = sorted(list(enumerate(distences)), reverse=True, key=lambda x:x[1])[1:6]

    for i in movies_list:
        print(new_df.iloc[i[0]].title)

In [100]:
recommend('Batman Begins')

The Dark Knight
Batman
Batman
The Dark Knight Rises
10th & Wolf

In [96]:
new_df.iloc[2405].title

'Aliens'

In [101]:
import pickle

In [103]:
pickle.dump(new_df, open('movies.pkl', 'wb'))

In [105]:
pickle.dump(new_df.to_dict(), open('movie_dict.pkl', 'wb'))

In [106]:
pickle.dump(similarity, open('similarity.pkl', 'wb'))